dist: xenial
sudo: required

language: python
python:
  - "3.7"
  - "3.8"

before_script: null

before_install:
    - python -m pip install --upgrade pip

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest pytest-cov pyyaml
    - source activate test-env
    - pip install --user -r requirements.txt                       
    - pip install configparser
    - pip install coveralls 

script: 
   
    - python -m pytest --cov=tests --cov-fail-under=50      # coveral fail threshold 90%
    
after_success:
  - coveralls 

  
defore_deploy:
    - gem install travis 
    
deploy :
    provider: pypi
    username: "__token__" # ${{ secrets.PYPI_USERNAME }} #"__token__"
    password: 
        secure: pypi-AgEIcHlwaS5vcmcCJDNkMzlhYTNhLWUxNjctNDg0ZS1hMDRlLTFjNmQwMTQ2MWJiMwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgLEagg-w3Xy8aoUWQ_zHyMpCaBR4lbxL1Mm6GKR8nKq8
        #${{ secrets.PYPI_PASSWORD }} # PYPI API token 
    on :
        branch: develop
    skip_existing: true
        
after_deploy:
    - pip search pycsamt 
    - pip show pycsamt
    - pip show https://pypi.org/project/pycsamt/
    
    
  
