language: python
python:
  - "3.7"
  - "3.8"
  # PyPy versions
  #- "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  #- "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
 virtualenv:
  system_site_packages: true
# command to install dependencies
#before_install:
#  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt #ip install --user -r requirements.txt fi python language is not used 
                                        # add --use-feature=2020-resolver if before install is uncommented 
  - pip install .
# command to run tests
script: pytest
