dist: xenial
sudo: required

language: python
python:
  - "3.7"

# command to install dependencies
before_script: null

before_install:
    - python -m pip install --upgrade pip

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest pytest-cov pyyaml
    - source activate test-env
    - pip install --user -r requirements.txt #ip install --user -r requirements.txt fi python language is not used 
                                            # add --use-feature=2020-resolver if before install is uncommented 
    #- conda install -c anaconda openpyxl # or python3 -m pip install --user xlsxwriter or pip3 install  openpyxl
    - pip install configparser
    - pip install coveralls 
    #- python3 -m pip install --user xlsxwriter
    - pip3 install openpyxl

# command to run tests
script:
    #- python -m unittest discover tests/ 
    # coveral test /tests modules /skpip test_makeborehole/failure under threshold 50% & make a report 
    - pytest -v --cov=tests/ --ignore=test_make_borehole.py --cov-fail-under=50 --cov-report=tests/

    
after_success:
  - coveralls
